export enum TicketStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  IN_SERVICE = "IN_SERVICE",
  REPLACEMENT_APPROVED = "REPLACEMENT_APPROVED",
  REPLACEMENT_DISPATCHED = "REPLACEMENT_DISPATCHED",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum ReplacementStatus {
  REQUESTED = "REQUESTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  DISPATCHED = "DISPATCHED",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
}

export enum ReturnStatus {
  REQUESTED = "REQUESTED",
  PICKUP_SCHEDULED = "PICKUP_SCHEDULED",
  PICKED_UP = "PICKED_UP",
  RECEIVED = "RECEIVED",
  CLOSED = "CLOSED",
}
